***NCDB 2015 Participant Use File, 2004-2015 Diagnosis Years***
***For Summer 2018 and Winter 2019 RFA***;
***Import, Value, and Variable Labels***
***Written in SAS 9.4***;

COMMENT This program will import the flat PUF text file and assign value and variable labels;
*To use this script, modify the line in the SAS syntax that reads LIBNAME library 'Z:\MyData' 
so that the text 'Z:\MyData' instead contains the location in which you want the SAS labels library 
to be saved. Now modify the line that reads INFILE 'Z:\MyData\flatfilename.dat' so that Z:\MyData\ 
instead has the path file where your .dat file is saved, and the text flatfilename has the 
actual name of the .dat file.;


dm 'log;clear;output;clear;odsresults;clear';
options mprint nodate pageno=1;
%SYSMSTORECLEAR; 


%let worklib=Z:\NCDB\NCDB PUFs May 2018\Lung PUF 2015\NCDB_PUF_DATA_Jun-07-2018-2\;

LIBNAME puf "&worklib";

/*load SAS Macro*/
%include "N:\medicare\NCDB\NCDB WorkShop\A Case Study\SAS macros\DICTIONARY V1.sas";

%macro makedata(site=);
/*load format*/
%include "&worklib.Format - Lung.sas";

/*load data*/
DATA puf.ncdb_&site.2015;
INFILE "&worklib.NCDBPUF_&site..0.2015.0.dat" 

TRUNCOVER lrecl=398;  

INPUT 
PUF_CASE_ID $ 1-37
PUF_FACILITY_ID $ 38-47
FACILITY_TYPE_CD  48-48
FACILITY_LOCATION_CD  49-49
AGE   50-52
SEX  53-53
RACE  54-55
SPANISH_HISPANIC_ORIGIN  56-56
INSURANCE_STATUS  57-58
MED_INC_QUAR_00  59-59
NO_HSD_QUAR_00  60-60
UR_CD_03  61-61
MED_INC_QUAR_12  62-62
NO_HSD_QUAR_12  63-63
UR_CD_13  64-64
CROWFLY  65-72
CDCC_TOTAL_BEST  73-74
SEQUENCE_NUMBER $ 75-76
CLASS_OF_CASE  77-78
YEAR_OF_DIAGNOSIS  79-82
PRIMARY_SITE $ 83-86
LATERALITY  87-87
HISTOLOGY  88-91
BEHAVIOR  92-92
GRADE  93-93
DIAGNOSTIC_CONFIRMATION  94-94
TUMOR_SIZE  95-97
REGIONAL_NODES_POSITIVE  98-99
REGIONAL_NODES_EXAMINED  100-101
DX_STAGING_PROC_DAYS  102-109
RX_SUMM_DXSTG_PROC  110-111
TNM_CLIN_T  $ 112-116
TNM_CLIN_N $ 117-121
TNM_CLIN_M $ 122-126
TNM_CLIN_STAGE_GROUP $ 127-130
TNM_PATH_T $ 131-135
TNM_PATH_N $ 136-140
TNM_PATH_M $ 141-145
TNM_PATH_STAGE_GROUP $ 146-149
TNM_EDITION_NUMBER  150-151
ANALYTIC_STAGE_GROUP  152-152
CS_METS_AT_DX $ 153-154
CS_METS_EVAL $ 155-155
CS_EXTENSION $ 156-158
CS_TUMOR_SIZEEXT_EVAL $ 159-159
CS_METS_DX_BONE  160-160
CS_METS_DX_BRAIN  161-161
CS_METS_DX_LIVER  162-162
CS_METS_DX_LUNG  163-163
LYMPH_VASCULAR_INVASION  164-164
CS_SITESPECIFIC_FACTOR_1  165-167
CS_SITESPECIFIC_FACTOR_2  168-170
CS_SITESPECIFIC_FACTOR_3  171-173
CS_SITESPECIFIC_FACTOR_4  174-176
CS_SITESPECIFIC_FACTOR_5  177-179
CS_SITESPECIFIC_FACTOR_6  180-182
CS_SITESPECIFIC_FACTOR_7  183-185
CS_SITESPECIFIC_FACTOR_8  186-188
CS_SITESPECIFIC_FACTOR_9  189-191
CS_SITESPECIFIC_FACTOR_10  192-194
CS_SITESPECIFIC_FACTOR_11  195-197
CS_SITESPECIFIC_FACTOR_12  198-200
CS_SITESPECIFIC_FACTOR_13  201-203
CS_SITESPECIFIC_FACTOR_14  204-206
CS_SITESPECIFIC_FACTOR_15  207-209
CS_SITESPECIFIC_FACTOR_16  210-212
CS_SITESPECIFIC_FACTOR_17  213-215
CS_SITESPECIFIC_FACTOR_18  216-218
CS_SITESPECIFIC_FACTOR_19  219-221
CS_SITESPECIFIC_FACTOR_20  222-224
CS_SITESPECIFIC_FACTOR_21  225-227
CS_SITESPECIFIC_FACTOR_22  228-230
CS_SITESPECIFIC_FACTOR_23  231-233
CS_SITESPECIFIC_FACTOR_24  234-236
CS_SITESPECIFIC_FACTOR_25  237-239
CS_VERSION_LATEST  240-245
DX_RX_STARTED_DAYS  246-253
DX_SURG_STARTED_DAYS  254-261
DX_DEFSURG_STARTED_DAYS  262-269
RX_SUMM_SURG_PRIM_SITE   270-271
RX_HOSP_SURG_APPR_2010  272-272
RX_SUMM_SURGICAL_MARGINS  273-273
RX_SUMM_SCOPE_REG_LN_SUR  274-274
RX_SUMM_SURG_OTH_REGDIS  275-275
SURG_DISCHARGE_DAYS  276-283
READM_HOSP_30_DAYS  284-284
REASON_FOR_NO_SURGERY  285-285
DX_RAD_STARTED_DAYS  286-293
RX_SUMM_RADIATION  294-294
RAD_LOCATION_OF_RX   295-295
RAD_TREAT_VOL  296-297
RAD_REGIONAL_RX_MODALITY  298-299
RAD_REGIONAL_DOSE_CGY  300-304
RAD_BOOST_RX_MODALITY  305-306
RAD_BOOST_DOSE_CGY  307-311
RAD_NUM_TREAT_VOL  312-314
RX_SUMM_SURGRAD_SEQ  315-315
RAD_ELAPSED_RX_DAYS  316-318
REASON_FOR_NO_RADIATION  319-319
DX_SYSTEMIC_STARTED_DAYS  320-327
DX_CHEMO_STARTED_DAYS  328-335
RX_SUMM_CHEMO  336-337
DX_HORMONE_STARTED_DAYS  338-345
RX_SUMM_HORMONE  346-347
DX_IMMUNO_STARTED_DAYS  348-355
RX_SUMM_IMMUNOTHERAPY   356-357
RX_SUMM_TRNSPLNT_ENDO   358-359
RX_SUMM_SYSTEMIC_SUR_SEQ  360-360
DX_OTHER_STARTED_DAYS  361-368
RX_SUMM_OTHER  369-369
PALLIATIVE_CARE  370-370
RX_SUMM_TREATMENT_STATUS  371-371
PUF_30_DAY_MORT_CD  372-372
PUF_90_DAY_MORT_CD  373-373
DX_LASTCONTACT_DEATH_MONTHS  374-381
PUF_VITAL_STATUS  382-382
RX_HOSP_SURG_PRIM_SITE  383-384
RX_HOSP_CHEMO  385-386
RX_HOSP_IMMUNOTHERAPY  387-388
RX_HOSP_HORMONE  389-390
RX_HOSP_OTHER  391-392
PUF_MULT_SOURCE 393-393
PUF_REFERENCE_DATE_FLAG 394-394
RX_SUMM_SCOPE_REG_LN_2012 395-395
RX_HOSP_DXSTG_PROC 396-397
PALLIATIVE_CARE_HOSP 398-398;


LABEL 
PUF_CASE_ID='Case Key'
PUF_FACILITY_ID='Facility Key'
FACILITY_TYPE_CD='Facility Type'
FACILITY_LOCATION_CD='Facility Location'
AGE='Age at Diagnosis'
SEX='Sex'
RACE='Race'
SPANISH_HISPANIC_ORIGIN='Spanish Hispanic Origin'
INSURANCE_STATUS='Primary Payor'
MED_INC_QUAR_00='Median Income Quartiles 2000'
NO_HSD_QUAR_00='Percent No High School Education Quartiles 2000'
UR_CD_03='Urban/Rural 2003'
MED_INC_QUAR_12='Census Median Income Quartiles 2007-2012'
NO_HSD_QUAR_12='Percent No High School Degree 2007-2012'
UR_CD_13='Urban/Rural 2013'
CROWFLY='Great Circle Distance'
CDCC_TOTAL_BEST='Charlson-Deyo Score'
SEQUENCE_NUMBER='Sequence Number'
CLASS_OF_CASE='Class of Case'
YEAR_OF_DIAGNOSIS='Year of Diagnosis'
PRIMARY_SITE='Primary Site'
LATERALITY='Laterality'
HISTOLOGY='Histology'
BEHAVIOR='Behavior'
GRADE='Grade'
DIAGNOSTIC_CONFIRMATION='Diagnostic Confirmation'
TUMOR_SIZE='Size of Tumor'
REGIONAL_NODES_EXAMINED='Regional Lymph Nodes Examined'
REGIONAL_NODES_POSITIVE='Regional Lymph Nodes Positive'
DX_STAGING_PROC_DAYS='Surgical Dx and Staging Procedure, Days from Dx'
RX_SUMM_DXSTG_PROC='Diagnostic and Staging Procedure'
TNM_CLIN_T='AJCC Clinical T'
TNM_CLIN_N='AJCC Clinical N'
TNM_CLIN_M='AJCC Clinical M'
TNM_CLIN_STAGE_GROUP='AJCC Clinical Stage Group'
TNM_PATH_T='AJCC Pathologic T'
TNM_PATH_N='AJCC Pathologic N'
TNM_PATH_M='AJCC Pathologic M'
TNM_PATH_STAGE_GROUP='AJCC Pathologic Stage Group'
TNM_EDITION_NUMBER='TNM Edition Number'
ANALYTIC_STAGE_GROUP='AJCC Analytic Stage Group'
CS_METS_AT_DX='Collaborative Stage Metastasis at Diagnosis'
CS_METS_EVAL='Collaborative Stage Metastasis Clinical/Pathological Prefix'
CS_EXTENSION='Collaborative Stage Tumor Extension'
CS_TUMOR_SIZEEXT_EVAL='Collaborative Stage Tumor Size Clinical/Pathological Prefix'
CS_METS_DX_BONE='Metastatic Bone Involvement'
CS_METS_DX_BRAIN='Metatstatic Brain Involvement'
CS_METS_DX_LIVER='Metastatic Liver Involvement'
CS_METS_DX_LUNG='Metastatic Lung Involvement'
LYMPH_VASCULAR_INVASION='Lymph Vascular Invastion'
CS_SITESPECIFIC_FACTOR_1='CS Site Specific Factor 1'
CS_SITESPECIFIC_FACTOR_2='CS Site Specific Factor 2'
CS_SITESPECIFIC_FACTOR_3='CS Site Specific Factor 3'
CS_SITESPECIFIC_FACTOR_4='CS Site Specific Factor 4'
CS_SITESPECIFIC_FACTOR_5='CS Site Specific Factor 5'
CS_SITESPECIFIC_FACTOR_6='CS Site Specific Factor 6'
CS_SITESPECIFIC_FACTOR_7='CS Site Specific Factor 7'
CS_SITESPECIFIC_FACTOR_8='CS Site Specific Factor 8'
CS_SITESPECIFIC_FACTOR_9='CS Site Specific Factor 9'
CS_SITESPECIFIC_FACTOR_10='CS Site Specific Factor 10'
CS_SITESPECIFIC_FACTOR_11='CS Site Specific Factor 11'
CS_SITESPECIFIC_FACTOR_12='CS Site Specific Factor 12'
CS_SITESPECIFIC_FACTOR_13='CS Site Specific Factor 13'
CS_SITESPECIFIC_FACTOR_14='CS Site Specific Factor 14'
CS_SITESPECIFIC_FACTOR_15='CS Site Specific Factor 15'
CS_SITESPECIFIC_FACTOR_16='CS Site Specific Factor 16'
CS_SITESPECIFIC_FACTOR_17='CS Site Specific Factor 17'
CS_SITESPECIFIC_FACTOR_18='CS Site Specific Factor 18'
CS_SITESPECIFIC_FACTOR_19='CS Site Specific Factor 19'
CS_SITESPECIFIC_FACTOR_20='CS Site Specific Factor 20'
CS_SITESPECIFIC_FACTOR_21='CS Site Specific Factor 21'
CS_SITESPECIFIC_FACTOR_22='CS Site Specific Factor 22'
CS_SITESPECIFIC_FACTOR_23='CS Site Specific Factor 23'
CS_SITESPECIFIC_FACTOR_24='CS Site Specific Factor 24'
CS_SITESPECIFIC_FACTOR_25='CS Site Specific Factor 25'
CS_VERSION_LATEST='CS Version Number'
DX_RX_STARTED_DAYS='Treatment Started, Days from Diagnosis'
DX_SURG_STARTED_DAYS='First Surgical Procedure, Days from Dx'
DX_DEFSURG_STARTED_DAYS='Definitive Surgical Procedure, Days from Dx'
RX_SUMM_SURG_PRIM_SITE='Surgical Procedure of Primary Site at any CoC Facility'
RX_HOSP_SURG_APPR_2010='Surgical Approach at this Facility'
RX_SUMM_SURGICAL_MARGINS='Surgical Margins Status at any CoC Facility'
RX_SUMM_SCOPE_REG_LN_SUR='Regional Lymph Node Surgery at any CoC Facility'
RX_SUMM_SURG_OTH_REGDIS='Surgery Other Site at any CoC Facility'
SURG_DISCHARGE_DAYS='Surgical Inpatient Stay, Days from Surgery'
READM_HOSP_30_DAYS='Readmission Within 30 Days of Surgical Discharge'
REASON_FOR_NO_SURGERY='Reason For No Surgery'
RX_SUMM_RADIATION='Radiation Therapy at any CoC Facility'
DX_RAD_STARTED_DAYS='Radiation, Days from Dx'
RAD_LOCATION_OF_RX='Location of Radiation Therapy'
RAD_TREAT_VOL='Radiation Treatment Volume'
RAD_REGIONAL_RX_MODALITY='Regional Treatment Modality'
RAD_REGIONAL_DOSE_CGY='Regional Dose'
RAD_BOOST_RX_MODALITY='Boost Treatment Modality'
RAD_BOOST_DOSE_CGY='Boost Dose'
RAD_NUM_TREAT_VOL='Number of Treatments to this Volume'
RX_SUMM_SURGRAD_SEQ='Radiation Surgery Sequence at any CoC Facility'
RAD_ELAPSED_RX_DAYS='Radiation Ended, Days from Start of Radiation'
REASON_FOR_NO_RADIATION='Reason For No Radiation'
DX_SYSTEMIC_STARTED_DAYS='Systemic, Days from Dx'
DX_CHEMO_STARTED_DAYS='Chemotherapy, Days from Dx'
RX_SUMM_CHEMO='Chemotherapy at any CoC Facility'
DX_HORMONE_STARTED_DAYS='Hormone Therapy, Days from Dx'
RX_SUMM_HORMONE='Hormone Therapy at any CoC Facility'
DX_IMMUNO_STARTED_DAYS='Immunotherapy, Days from Dx'
RX_SUMM_IMMUNOTHERAPY='Immunotherapy at any CoC Facility'
RX_SUMM_TRNSPLNT_ENDO='Hematologic Transplant and Endocrine Procedures at any CoC Facility'
RX_SUMM_SYSTEMIC_SUR_SEQ='Systemic/Surgery Sequence'
DX_OTHER_STARTED_DAYS='Other Treatment, Days from Dx'
RX_SUMM_OTHER='Other Treatment at any CoC Facility'
PALLIATIVE_CARE='Palliative Care'
RX_SUMM_TREATMENT_STATUS='Received Treatment or Active Surveillance'
PUF_30_DAY_MORT_CD='30 Day Mortality'
PUF_90_DAY_MORT_CD='90 Day Mortality'
DX_LASTCONTACT_DEATH_MONTHS='Last Contact or Death, Months from Dx'
PUF_VITAL_STATUS='Vital Status'
RX_HOSP_SURG_PRIM_SITE='Surgery of Primary Site at this Facility'
RX_HOSP_CHEMO='Chemotherapy at this Facility'
RX_HOSP_IMMUNOTHERAPY='Immunotherapy at this Facility'
RX_HOSP_HORMONE='Hormone Rx at this Facility'
RX_HOSP_OTHER='Other Rx at this Facility'
PUF_MULT_SOURCE='Patient Treated in > 1 CoC Facility?'
RX_HOSP_DXSTG_PROC='Diagnostic and Staging Procedure at this Facility'
PALLIATIVE_CARE_HOSP='Palliative Care at this Facility';


FORMAT FACILITY_TYPE_CD ffacility. FACILITY_LOCATION_CD ffac_location. AGE fage. 
RACE frace. SEX fsex. INSURANCE_STATUS finsurance. SPANISH_HISPANIC_ORIGIN fhispanic.
CDCC_TOTAL_BEST fcdcc.
MED_INC_QUAR_00 f00income.  NO_HSD_QUAR_00 f00hsd. MED_INC_QUAR_12 F12income. NO_HSD_QUAR_12 F12hsd.
UR_CD_03 UR_CD_13 fur03_cd.  CLASS_OF_CASE fclass. YEAR_OF_DIAGNOSIS fdxyear.
LATERALITY flat. BEHAVIOR fbeh. GRADE fgrade.  
TUMOR_SIZE ftumor. REGIONAL_NODES_EXAMINED fnodes_examined. REGIONAL_NODES_POSITIVE fnodes_positive.
DX_STAGING_PROC_DAYS fstaging_proc. RX_SUMM_DXSTG_PROC RX_HOSP_DXSTG_PROC fsdxstg.
TNM_EDITION_NUMBER ftnmedit.
ANALYTIC_STAGE_GROUP  DX_RX_STARTED_DAYS fdxrxdays.
DX_SURG_STARTED_DAYS fdxrxdays. DX_DEFSURG_STARTED_DAYS fdxrxdays. RX_HOSP_SURG_APPR_2010 fapproach.
RX_SUMM_SURGICAL_MARGINS fsurgmargin.  RX_SUMM_SCOPE_REG_LN_SUR FRXSUMM_Scope_Reg_Ln_Surg.
RX_SUMM_SURG_OTH_REGDIS fsurgotherregdis. SURG_DISCHARGE_DAYS fsurgdischdays.
READM_HOSP_30_DAYS freadmission. REASON_FOR_NO_SURGERY freasonnosurg.
RX_SUMM_RADIATION fradtype.
RAD_LOCATION_OF_RX fradlocation. RAD_TREAT_VOL fradvol. RAD_REGIONAL_RX_MODALITY fregrxmod.
RAD_REGIONAL_DOSE_CGY fradregdose. RAD_BOOST_RX_MODALITY fboostmodality.
RAD_BOOST_DOSE_CGY fboostdose. RAD_NUM_TREAT_VOL fradnumtrt.
RX_SUMM_SURGRAD_SEQ fsurgradseq. RAD_ELAPSED_RX_DAYS fradelapsed.
REASON_FOR_NO_RADIATION freasonnorad. DX_SYSTEMIC_STARTED_DAYS frxdays.
DX_CHEMO_STARTED_DAYS frxdays. RX_SUMM_CHEMO RX_HOSP_CHEMO fchemo. DX_HORMONE_STARTED_DAYS frxdays. 
RX_SUMM_HORMONE RX_HOSP_HORMONE fhormone. DX_IMMUNO_STARTED_DAYS frxdays. 
RX_SUMM_IMMUNOTHERAPY RX_HOSP_IMMUNOTHERAPY fimmuno. 
RX_SUMM_TRNSPLNT_ENDO ftrnsplntendo. RX_SUMM_OTHER RX_HOSP_OTHER fotherrx.
PALLIATIVE_CARE  PALLIATIVE_CARE_HOSP fpalliative. RX_SUMM_SYSTEMIC_SUR_SEQ fsurgsysseq.
PUF_VITAL_STATUS fvital. RX_SUMM_TREATMENT_STATUS FRxstatus. CS_METS_DX_BONE
CS_METS_DX_BRAIN CS_METS_DX_LIVER CS_METS_DX_LUNG CSMETSSITE.  LYMPH_VASCULAR_INVASION Flymph.
PUF_30_DAY_MORT_CD f30day. PUF_90_DAY_MORT_CD f90day. PUF_MULT_SOURCE Fmultiple.

TUMOR_SIZE ftumorsize. REGIONAL_NODES_EXAMINED fnodes_examined_. REGIONAL_NODES_POSITIVE fnodes_positive_.
PRIMARY_SITE $fprimsite. DIAGNOSTIC_CONFIRMATION fdiagconfirm.;


/*Recode missing for radiation dose variables, some Days variable*/
if RAD_REGIONAL_DOSE_CGY in (0, 88888,99999) then RAD_REGIONAL_DOSE_CGY  = .;
if RAD_BOOST_DOSE_CGY in (0, 88888,99999) then RAD_BOOST_DOSE_CGY = .;
if RAD_NUM_TREAT_VOL in (0,999) then RAD_NUM_TREAT_VOL =.;
if RAD_ELAPSED_RX_DAYS  in (0, 999) then RAD_ELAPSED_RX_DAYS  = .;

RUN;
%mend;

dm 'log;clear;output;clear;odsresults;clear';
%makedata(site=LungNSC);

%macro freqsite(site=);
proc freq data=puf.ncdb_&site.2015;;
table TUMOR_SIZE PRIMARY_SITE  
CS_SITESPECIFIC_FACTOR_1 CS_SITESPECIFIC_FACTOR_2 CS_SITESPECIFIC_FACTOR_3 CS_SITESPECIFIC_FACTOR_4 
CS_SITESPECIFIC_FACTOR_5 CS_SITESPECIFIC_FACTOR_6 CS_SITESPECIFIC_FACTOR_7 CS_SITESPECIFIC_FACTOR_8 
CS_SITESPECIFIC_FACTOR_9 CS_SITESPECIFIC_FACTOR_10 CS_SITESPECIFIC_FACTOR_11 CS_SITESPECIFIC_FACTOR_12 
CS_SITESPECIFIC_FACTOR_13 CS_SITESPECIFIC_FACTOR_14 CS_SITESPECIFIC_FACTOR_15 CS_SITESPECIFIC_FACTOR_16 
CS_SITESPECIFIC_FACTOR_17 CS_SITESPECIFIC_FACTOR_18 CS_SITESPECIFIC_FACTOR_19 CS_SITESPECIFIC_FACTOR_20 
CS_SITESPECIFIC_FACTOR_21 CS_SITESPECIFIC_FACTOR_22 CS_SITESPECIFIC_FACTOR_23 CS_SITESPECIFIC_FACTOR_24 

;
run;
%mend;

%freqsite(site=LungNSC);

dm 'log;clear;output;clear;odsresults;clear';

%macro rundicionary(site=);
libname ld "&worklib.HyperLink.xlsx";

data &site.dic;
  set ld.'dictionary$'n;
run;

Ods listing close;
ods html close;
option;

%DICTIONARY(
DATASET=puf.ncdb_&site.2015, 

CLIST=FACILITY_TYPE_CD FACILITY_LOCATION_CD  SEX RACE SPANISH_HISPANIC_ORIGIN INSURANCE_STATUS 
                  MED_INC_QUAR_00  NO_HSD_QUAR_00 UR_CD_03 MED_INC_QUAR_12 NO_HSD_QUAR_12 UR_CD_13  
                  CDCC_TOTAL_BEST SEQUENCE_NUMBER CLASS_OF_CASE YEAR_OF_DIAGNOSIS  PRIMARY_SITE LATERALITY 
                  HISTOLOGY BEHAVIOR GRADE DIAGNOSTIC_CONFIRMATION TUMOR_SIZE REGIONAL_NODES_POSITIVE REGIONAL_NODES_EXAMINED  
                  RX_SUMM_DXSTG_PROC  TNM_CLIN_T  TNM_CLIN_N TNM_CLIN_M TNM_CLIN_STAGE_GROUP TNM_PATH_T TNM_PATH_N 
                  TNM_PATH_M TNM_PATH_STAGE_GROUP TNM_EDITION_NUMBER ANALYTIC_STAGE_GROUP CS_METS_AT_DX CS_METS_EVAL 
                  CS_EXTENSION CS_TUMOR_SIZEEXT_EVAL CS_METS_DX_BONE CS_METS_DX_BRAIN CS_METS_DX_LIVER CS_METS_DX_LUNG 
                  LYMPH_VASCULAR_INVASION 
				  CS_SITESPECIFIC_FACTOR_1 CS_SITESPECIFIC_FACTOR_2 CS_SITESPECIFIC_FACTOR_3 CS_SITESPECIFIC_FACTOR_4 
				  CS_SITESPECIFIC_FACTOR_5 CS_SITESPECIFIC_FACTOR_6 CS_SITESPECIFIC_FACTOR_7 CS_SITESPECIFIC_FACTOR_8 
				  CS_SITESPECIFIC_FACTOR_9 CS_SITESPECIFIC_FACTOR_10 CS_SITESPECIFIC_FACTOR_11 CS_SITESPECIFIC_FACTOR_12 
				  CS_SITESPECIFIC_FACTOR_13 CS_SITESPECIFIC_FACTOR_14 CS_SITESPECIFIC_FACTOR_15 CS_SITESPECIFIC_FACTOR_16 
				  CS_SITESPECIFIC_FACTOR_17 CS_SITESPECIFIC_FACTOR_18 CS_SITESPECIFIC_FACTOR_19 CS_SITESPECIFIC_FACTOR_20 
				  CS_SITESPECIFIC_FACTOR_24 CS_SITESPECIFIC_FACTOR_22 CS_SITESPECIFIC_FACTOR_23 CS_SITESPECIFIC_FACTOR_24 
				  CS_SITESPECIFIC_FACTOR_25
                  CS_VERSION_LATEST RX_SUMM_SURG_PRIM_SITE  RX_HOSP_SURG_PRIM_SITE RX_HOSP_SURG_APPR_2010 RX_SUMM_SURGICAL_MARGINS 
                  RX_SUMM_SURG_OTH_REGDIS  READM_HOSP_30_DAYS REASON_FOR_NO_SURGERY RX_SUMM_RADIATION RAD_LOCATION_OF_RX  RAD_TREAT_VOL 
                  RAD_REGIONAL_RX_MODALITY RAD_BOOST_RX_MODALITY RX_SUMM_SURGRAD_SEQ REASON_FOR_NO_RADIATION  RX_SUMM_CHEMO  RX_SUMM_HORMONE 
                  RX_HOSP_HORMONE RX_SUMM_IMMUNOTHERAPY RX_SUMM_TRNSPLNT_ENDO RX_SUMM_SYSTEMIC_SUR_SEQ RX_SUMM_TREATMENT_STATUS
                  RX_SUMM_OTHER PALLIATIVE_CARE PUF_30_DAY_MORT_CD PUF_90_DAY_MORT_CD PUF_VITAL_STATUS RX_HOSP_CHEMO  RX_HOSP_IMMUNOTHERAPY  
                  RX_HOSP_OTHER PUF_MULT_SOURCE REFERENCE_DATE_FLAG RX_SUMM_SCOPE_REG_LN_2012 RX_HOSP_DXSTG_PROC PALLIATIVE_CARE_HOSP,

NLIST = CROWFLY AGE DX_STAGING_PROC_DAYS RAD_REGIONAL_DOSE_CGY RAD_BOOST_DOSE_CGY RAD_NUM_TREAT_VOL DX_RX_STARTED_DAYS 
        DX_SURG_STARTED_DAYS DX_DEFSURG_STARTED_DAYS SURG_DISCHARGE_DAYS DX_RAD_STARTED_DAYS RAD_ELAPSED_RX_DAYS DX_SYSTEMIC_STARTED_DAYS 
        DX_CHEMO_STARTED_DAYS DX_HORMONE_STARTED_DAYS DX_IMMUNO_STARTED_DAYS DX_OTHER_STARTED_DAYS DX_LASTCONTACT_DEATH_MONTHS, 

CSV=F,
OUTPATH=Z:\NCDB\Data Dictionary\, 
FNAME=NCDB PUF &site 2015 Data Dictionary_PI-Madhu, 
link=T,
linkdata=&site.dic,
mergevar=name,
linkvar=website,
DEBUG=F); 
%mend;

dm 'log;clear;output;clear;odsresults;clear';
%rundicionary(site=LungNSC);

